### ISSUE TITLE
API Version not compatible with latest build (Windows 0.4.1)

### ISSUE THREAD

**Issue by Moddler** [majekw/sigrok-ccd-pd#1]
When trying to load the decoder into the latest version (Windows 0.4.1) the log shows an error message:

srd: Only PD API version 3 is supported, decoder ccd has version 2.
srd: Failed to load decoder ccd: API version mismatch

**Comment by majekw** [comment]
Yes, it's still on my TODO list to rewrite it to newer API :-(
I hope that before summer I could do that.

Do you have some dumps for testing? I have only from Jeep ZJ '98, but messages from other years or cars can be different.

**Comment by Moddler** [comment]
I can create any dump needed from a 1995 Chrysler Voyager Minivan. 
I also have two sets of Bodycomputer + Instrument Cluster (digital and analog Version) i could sniff on.
I would be very happy to help wherever i can.

**Comment by Moddler** [comment]
I asked some people i know and i might be able to read a WJ and a ZJ. Additionally a AS Body Minivan. I also have a DRB II diagnostic device i could read the diagnostic commands from the device.

For sniffing cars i think a standardised procedure would be good.
- No Key -> Key in lock
- Key Off -> Key On
- Key On -> Start Engine 
- Idle
- Idle -> Off

Specific commands like from the DRB should be then Sniffed standalone.

Specific fuctions (like windows up/down, door locking) should be known beforehand and den specifically looked for (i have no idea what functions may be relevant for CCD in a ZJ/WJ/Minivan and what to sniff for)

**Comment by majekw** [comment]
I pushed very ugly fix for API 3. It works, but eats a lot of cpu and patience is required to process all samples. I need to rewrite it later in proper way.

As for dumps I'm just curious how different messages are in other car. I think that I create separate directory for it. But let's discuss about dumps here: https://github.com/majekw/sigrok-ccd-pd/issues/2

**Comment by majekw** [comment]
I'm closing this. Optimization is another story :-)
